.PHONY: clean All

All:
	@echo "----------Building project:[ Section014OperatorOverloading - Debug ]----------"
	@cd "Challenge014OperatorOverloading" && "$(MAKE)" -f  "Section014OperatorOverloading.mk"
clean:
	@echo "----------Cleaning project:[ Section014OperatorOverloading - Debug ]----------"
	@cd "Challenge014OperatorOverloading" && "$(MAKE)" -f  "Section014OperatorOverloading.mk" clean
