.PHONY: clean All

All:
	@echo "----------Building project:[ Section4Challenge - Debug ]----------"
	@cd "FirstProgram" && "$(MAKE)" -f  "Section4Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section4Challenge - Debug ]----------"
	@cd "FirstProgram" && "$(MAKE)" -f  "Section4Challenge.mk" clean
