.PHONY: clean All

All:
	@echo "----------Building project:[ Section010LetterPyramid - Debug ]----------"
	@cd "Section010LetterPyramid" && "$(MAKE)" -f  "Section010LetterPyramid.mk"
clean:
	@echo "----------Cleaning project:[ Section010LetterPyramid - Debug ]----------"
	@cd "Section010LetterPyramid" && "$(MAKE)" -f  "Section010LetterPyramid.mk" clean
